from pathlib import Path
import json,hashlib
doc=Path(r'E:/Project/Godot/这次怎么逃/docs/art/architecture-v30');root=doc.parents[2]
t=json.loads((doc/'final-task-read.json').read_text(encoding='utf-8-sig'));d=json.loads((doc/'delivery.json').read_text(encoding='utf-8-sig'))
assert all(hashlib.sha256((root/f['path']).read_bytes()).hexdigest()==f['sha256'] for f in d['files'])
summary='交付'+d['version']+'，48文件hash冻结：内置imagegen按人类批准自然砌接概念重绘新RGBA主图，普通横向压顶石+窄中央头石+两竖石，取消V29整块凸T/大三角肩部/密亮斑。PNG原输出字节copy未涂改，旧V24–29所有冻结文件hash均未改。20/24本体132/136×80、stemx56、北横逻辑24、下口80，4源区同一新图，v10两独立MeshTexture图标GPU实际可见。初轮actual发现有效横臂多约3world深而覆盖感突出，已只改新图源注册为y278..438，末部原透明带令可见约21；stem源y438续出，两厨房cap_cutouts27.48保留原H底沿，外围L30.48不动；物理20/24不改。修正版actual亲眼审1200左右game/editor右、960game右/editor左、分类图及独立两尺寸，对批准图普通石缝续接/同底线，无独立额外暗底、透明带漏地、整T牌；顶面有轻微正常石色/磨损变化，不承诺逐像素照搬。主美判可独立审。两尺寸T26+palette40+独立12共78技术项与规则73全部通过，检查数单列不代替审美。P63仅登记/白名单新建换V30、历史V29仍兼容，原墙身/柱楣/外围L/长V27保留。actual原字节复制、提示词/接口/源审/主美审美记录与交付hash齐备；主美没有shared脚本/data/Git写入。待制作人独立验收，不代表人类已对新实际图再批准。'
paths=['art/architecture/v30/manifest.json','art/architecture/v30/cafeteria_t_master_v30.png','art/editor/v10/manifest.json','docs/art/architecture-v30/delivery.json','docs/art/architecture-v30/README.md','docs/art/architecture-v30/prompt.json','docs/art/architecture-v30/interface.json','docs/art/architecture-v30/source-review.json','docs/art/architecture-v30/native-preview.png','docs/art/architecture-v30/native-detail.png','docs/art/architecture-v30/native-icons-visible.json','docs/art/architecture-v30/p63-visual-review.md','docs/art/architecture-v30/p63-visual-evidence.json','docs/art/architecture-v30/approved-reference.png','docs/art/architecture-v30/runtime/p63-1200-runtime-t-left.png','docs/art/architecture-v30/runtime/p63-1200-runtime-t-right.png','docs/art/architecture-v30/runtime/p63-1200-editor-t-right.png','docs/art/architecture-v30/runtime/p63-960-runtime-t-right.png','docs/art/architecture-v30/runtime/p63-960-editor-t-left.png','docs/art/architecture-v30/runtime/p63-1200-t-palette.png','docs/art/architecture-v30/runtime/p63-runtime-t-components.png','docs/art/architecture-v30/runtime/p63-runtime-t-components.json','docs/art/architecture-v30/runtime/p63-access-access-headless-1200.json']
out=dict(taskId=t['task']['id'],revision=t['revision'],feedbackId='a30-final-v30-20261007',status='待验收',summary=summary,evidence=[str(root/p) for p in paths],requestId='a30-final-v30-20261007')
assert all(Path(p).is_file() for p in out['evidence'])
(doc/'final-feedback.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'version':d['version'],'hashes_match':True,'files':len(d['files'])}))
