from pathlib import Path
import json,hashlib
root=Path(r'E:/Project/Godot/这次怎么逃');doc=root/'docs/art/architecture-v31';doc.mkdir(parents=True,exist_ok=True)
tex='res://art/architecture/v24/cafeteria_portal_v24.png'
sha=hashlib.sha256((root/'art/architecture/v24/cafeteria_portal_v24.png').read_bytes()).hexdigest()
run_scale=144/573;yscale=121.5/375;window=[232,192,245,24/yscale];period=245*run_scale
rows=[]
for cross in [20,24]:
    width=112+cross;id='cafeteria_t_20_v31' if cross==20 else 'cafeteria_t_v31'
    patches=[]
    for src,dst,transpose,role in [([140,192,width/run_scale,window[3]],[0,0,width,24],False,'horizontal_cap'),([232+(period-3)/run_scale,192,3/run_scale,window[3]],[56,21,cross,3],True,'longitudinal_stem'),([232,192,56/run_scale,window[3]],[56,24,cross,56],True,'longitudinal_stem')]:
        patches.append(dict(source=src,destination=dst,transpose=transpose,mirror_x=False,rotation_quarters=0,modulate=[1,1,1,1],role=role))
    rows.append(dict(id=id,name='同源石墙T接口·'+str(cross)+'厚',texture=tex,texture_size=[2170,725],region=[0,0,2170,725],world_size=[width,80],render_size=[width,80],render_mode='architecture_junction_t',assembly_patches=patches,cross_width_world=cross,stem_rect=[56,24,cross,56],north_bar_rect=[0,0,width,24],return_start_world=80,tile_period_world=period,source_repeat_window=window,blocking=False,interactive=False,shadow_baked=False,self_shading_baked=True,source_coordinate_space='absolute original PNG pixels',sha256=sha,alpha_core_shader='res://art/architecture/v25/safe_edges_v25.gdshader',editor_icon='res://art/editor/v11/icons/'+id+'.tres'))
m=dict(schema=2,version='architecture-v31-20261007',style='SAME-SOURCE-TOP-AND-SIDE-V27',master_texture=tex,master_sha256=sha,edge_shader='res://art/architecture/v25/safe_edges_v25.gdshader',physical_contract={'exterior_width':24,'interior_width':20,'front_height':90,'door_width':180},assets=rows)
interface=dict(schema=2,manifest='res://art/architecture/v31/manifest.json',source_png=tex,source_sha256=sha,new_production_png_count=0,sizes={'20':[132,80],'24':[136,80]},stem_x=56,bar_depth=24,stem_bottom_y=80,source_repeat_window=window,world_stone_pitch=period,stem_source=[232,192,56/run_scale,window[3]],stem_transpose=True,run_scale_world_per_source_pixel=run_scale,source_cross=window[3],contact_rect=[56,21,'cross',3],contact_source=[232+(period-3)/run_scale,192,3/run_scale,window[3]],contact_phase=-3,contact_policy='Producer agreed same-source3world contact bridge at local21..24 as explicit exception; main stem remains24..80. UV tail of previous V27 cycle joins phase0 at24, no PNG edit or horizontal cap replacement.',phase_origin_local_y=24,phase_at_local80=56,next_seam_local_y=24+period,roles={'horizontal_cap':'complete north bar, for standalone placement and complete MeshTexture icon','longitudinal_stem':'y24..80 same V27 top/side UV, default side dark at right'},kitchen={'reuse_cap':True,'draw_roles':['longitudinal_stem'],'cap_cutouts':'remove both T30 cutouts completely; original H cap remains','face_stem_replacement_local_y_start':24,'tile_origin_y':1170.48,'render_top_start':1226.48,'tile_origin_from_T_origin':24,'render_start_from_T_origin':80,'right_T_mirror_x':True,'right_V27':'cafeteria_wall_v_r_20_v27','left_V27':'cafeteria_wall_v_l_20_v27'},phase_policy='V27 tile origin at T local24; clip first V run below local80, never restart window232 at local80. At boundary sourceX=454.8333333333333 on both sides. Repeat period61.57068062827225, no phase_axis fields/full-PNG shifts.',horizontal_policy='Same original H cap source [140,192] at scale144/573, cross24. Kitchen keeps actual old H UV unchanged, does not overlay horizontal_cap.',mirror_policy='Default T stem transpose, mirror false. Right kitchen wholeT mirror true matches V27_r; no second patch mirror. Run direction unchanged.',review='compare complete two kitchen vertical walls from T to bottom end against user mismatch screenshot, not only closeup of T')
for rel,obj in [('art/architecture/v31/manifest.json',m),('art/editor/v11/manifest.json',dict(schema=1,assets=[dict(id=a['id'],name=a['name'],category='furniture',editor_icon=a['editor_icon']) for a in rows],tools=[])),('docs/art/architecture-v31/interface.json',interface)]:
    p=root/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'components':2,'source_sha256':sha,'new_png':0,'period':period,'stem_source_width':56/run_scale,'phase_at80':56}))

